// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igmcbzilqmoxkwjgnrij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnbWNiemlscW1veGt3amducmlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjk0MTEsImV4cCI6MjA2MzkwNTQxMX0.aQ4Zk_FX89kXeOWxAnRrW3t3oMu06tDjDVE8vNRc4mg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);